EOS-uiux-Solutions/eos-icons-landing

.github/workflows/deploy.yml

This PR fixes the issues in Actions for the Deploy job that is not creating the config json necessary to build the page.

add steps to update eos-icons and create teh config file

---

public/index.html

Added structured data

---

src/pages/AboutPage.jsx
src/pages/Docs.js
src/pages/Home.js
src/pages/TeamPage.jsx
src/utils/scrollToTop.js

This issue needs a scroll function (defined in the /src/utils/scrollToTop.js) to be called each time a page component is getting rendered, for that reason that function is being called to the pages in the useEffect section.

"Solved the #24 issue - added scrollToTop.js under utils folder and updated the pages files with this"

---

src/components/Tabs.js
src/modules/IconsSet.js

While switching to animated icons tab and selecting them, the current behaviour of code is that search field is not  populated and url also doesn't point to icon. The code fix aim to fill the input element by setting searchValue state and setting url.

[Issue 10]:Search field bug in animated icons

---

src/components/Tabs.js
src/pages/Docs.js

Fixed default view of Docs Page. On first load docs Page will look like below -

Fixed default view of Docs Page

---

src/pages/Cookies.js
src/pages/Docs.js
src/pages/TeamPage.jsx

Fixes #13 
I have replaced all non-consecutive heading tags with consecutive tags, in accordance to https://suse.eosdesignsystem.com.

Issue #13: Replaced heading tags

---

src/components/HowToPanel.js

Solved Issue#27 : Download Icon Bug

---

src/assets/scss/components/icon-list.scss

fixes: #41 
https://user-images.githubusercontent.com/44670961/154950711-01dececf-5d43-4e1c-8ac2-f7423193d7e0.mp4
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

Fixed: #41: Updated Suggested search text to have pointer cursor

---

src/assets/scss/pages/docs.scss
src/pages/Docs.js
src/utils/Contributors.store.js

Fixed #44 Added various improvements fixing typos, dead link and various responsiveness issues.

Various improvements added

---

public/index.html

Fixed #14 added more meta tags including primary meta tags, added description to the facebook meta tags and added twitter meta tags.
The description added in the meta tags are fetched from About-Us page where description is defined for the meta tag.

Added necessary meta tags

---

src/assets/scss/base/prism-theme.scss
src/pages/Cookies.js

fixes: #55 
https://user-images.githubusercontent.com/44670961/155221507-c5324a42-49ca-4b10-a366-d876f439ec38.mp4
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

Fixed: #55 Updated the z-index of codeblock & also added a space in cookies page between a text & a link

---

src/assets/scss/components/icon-list.scss

Fixed #53: White space reduced between icon sections

---

.github/ISSUE_TEMPLATE/bug.yml

Bug Issue template (GitHub issue form)

added bug issue template

---

src/pages/AboutPage.jsx
src/pages/Docs.js

Reverts EOS-uiux-Solutions/eos-icons-landing#78

Revert "Fixed broken gitlab links in Docs and About Us Pages"

---

src/assets/scss/components/select.scss
src/assets/scss/variables/components/select.scss

fixes: #46 
https://user-images.githubusercontent.com/44670961/154821094-8c589d70-ce8f-4f41-ab1c-74a40c53687b.mp4
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

Fixed: #46: Added Border & Reduced the space between down arrow icon & option text

---

src/pages/Docs.js

Added responsiveness to the table in the Vue section in the Docs Page.

---

.github/ISSUE_TEMPLATE/feature_request.yml
package-lock.json

Created a template for users to file for new issues. Please let me know if any fields are required to be added/removed. Thanks :) 
Fixes #87

added feature request template

---

src/assets/scss/components/navigation.scss

The thickness of the blue line is now similar under all the sections at Navbar

fixed the blue line thickness #95

---

src/utils/Links.store.js

Footer had a small typo.
- changed **colaborate** to **collaborate**

fixed footer typo

---

src/components/CustomizeIconsPanel.js

Fixed #98  Added an alert state to the multiple icons when no icon is selected.

Added Alert for when no font is selected

---

src/components/CookiesBanner.js
src/utils/EosIcons.store.js

Fixes #92 
Video after fixing issue:
https://user-images.githubusercontent.com/72144454/158033578-0dadf595-d140-4f6a-9b56-8fe4ed84776b.mp4

Fix: #92 - modified CookiesBanner

---

src/assets/scss/base/spacing.scss
src/components/Navigation.js

aligned the navbar elements
Fix for issue : #89

Navbar elements alignment

---

src/components/IconDisplay.js
src/modules/IconsSet.js

Fixes #122. Wrap animated Icons in the IconDisplay component to make it more organized.

wrap animated icons in IconDisplay component

---

package-lock.json
package.json
src/components/HowToPanel.js

Added toast msg feature
Demo SS:
The toast msg pops up in the upper center position of the window

Added toast msg feature

---

src/pages/Home.js

Yesterday 3 week old PR #81 got merged. The repo had a conflict back then when the PR was raised causing build failures. Although I fixed that immediately back then but due to the changes that got merged yesterday, new PRs are having failed build checks. I am fixing those build fails in this PR. There's not much in this PR. Please review

fixing build fail caused by merging of an old PR #81

---

src/assets/scss/pages/page-not-found.scss
src/pages/PageNotFound.js

Fixed #111 I have Refactored the 404 page and added a button to link back to the Homepage, created a new Pull Request because other one is creating conflict issues.

Refactored the 404 page 
